ProActive.tryWithCatch(MyException.class);
// Just before the try
try { 
      // Asynchronous calls with exceptions 
      .....
      // One can use PAException.throwArrivedException() and 
      // PAException.waitForPotentialException() here 
      
      // At the end of the try
      PAException.endTryWithCatch();
   } catch (MyException e) { 
	   // ... 
   } finally { 
	   // At the beginning of the finally
	   PAException.removeTryWithCatch();
}